name: acrordrdc
title: Adobe Acrobat Reader (WINE)
summary: Adobe Acrobat Reader is a pdf reader & Web services developed by Adobe Inc.
description: |
  Adobe Acrobat Reader DC software is the free global standard for reliably viewing, printing, and commenting on PDF documents.

  And now, it's connected to the Adobe Document Cloud − making it easier than ever to work across computers and mobile devices.

  It's the only PDF viewer that can open and interact with all types of PDF content, including forms and multimedia.
adopt-info: acrordrdc

grade: stable
confinement: strict
architectures:
  - build-on: amd64
    run-on: [amd64, i386]
base: core18

plugs:
  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  wine-5-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-5-stable

environment:
  WINEARCH: "win32"
  WINEDLLOVERRIDES: "mscoree,mshtml="   # Prevent pop-ups about Wine Mono and Wine Gecko

apps:
  acrordrdc:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier run-exe
    environment:
      RUN_EXE: "C:/Program Files/Adobe/Acrobat Reader DC/Reader/AcroRd32.exe"
    plugs:
      - cups-control
      - home
      - network
      - removable-media
      - opengl

  wine:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier
    plugs:
      - home
      - network
  winetricks:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier winetricks
    plugs:
      - network

parts:
  acrordrdc:
    plugin: nil
    source: ./snap/local/src
    override-build: |
      snapcraftctl build
      set -ex
      ver=$(wget -qO- https://helpx.adobe.com/acrobat/release-note/release-notes-acrobat-reader.html | grep "dccontinuousdectwentytwentyooc" | sed 's|(| |g;s|)| |g' | awk 'FNR == 1 {next} {print $6}' | head -n1)
      snapcraftctl set-version "20$ver"
      mkdir -p sommelier/hooks ; mv pre-install sommelier/hooks ; cp -R -p sommelier $SNAPCRAFT_PART_INSTALL
    stage:
      - sommelier
    build-packages:
      - wget

  # The sommelier script helps you snap Windows applications using Wine. It 
  # initializes and configures Wine and installs the Windows application.
  sommelier:
    plugin: make
    source: https://github.com/mmtrt/sommelier-core.git
    source-branch: "winetricks-fix-patch"

  fixup-url:
    after: [sommelier]
    plugin: nil
    override-build: |
      lver=$(wget -qO- https://helpx.adobe.com/acrobat/release-note/release-notes-acrobat-reader.html | grep "dccontinuousnovember2020" | sed 's|(| |g;s|)| |g' | awk 'FNR == 1 {next} {print $6}' | tr -d '.' | head -n1)
      sed -i "s|XXX|$lver|g" ../../acrordrdc/install/sommelier/hooks/pre-install
